Aggiunta Segnalazione Bean e DAO
Nio1998/WePlay pull request #6
Opened 2024-12-07 15:39 UTC by gxanlvxgx

2024-12-07 17:18 UTC, andr3w003 requested changes
Comunque nel try delle funzioni, `Connection connection = ConDB.getConnection();` non dovrebbe stare tra parentesi, perchè così la connessione si chiude al termine del try, invece dovrebbe stare all'interno del try e in un finally si dobrebbe chiamare `ConDB.releaseConnection(connection);` per restituire la connessione al pool.
In realtà alla fine funziona lo stesso anche com'è adesso, ma è più corretto restituire la connessione al pool.

2024-12-07 17:18 UTC, andr3w003 commented on Application/src/main/.DS_Store
Da eliminare questo file

2024-12-07 17:18 UTC, andr3w003 commented on Application/src/main/java/model/SegnalazioneDAO.java
> +	        preparedStatement.setString(2, "in attesa"); // Stato predefinito
Per lo stato si dovrebbe comunque usare quello che sta nella segnalazione passata come parametro della funzione.

```suggestion
	        preparedStatement.setString(2, segnalazione.getStato()); // Colonna stato
```

2024-12-08 15:44 UTC, gxanlvxgx commented on Application/src/main/.DS_Store
non me lo fa eliminare non so perchè

2024-12-08 17:05 UTC, andr3w003 approved these changes

2024-12-08 17:05 UTC, merged