Aggiunto ValutazioneBean e ValutazioneDAO nella cartella Valutazione
Nio1998/WePlay pull request #8
Opened 2024-12-08 20:49 UTC by pummarolaalragu

Vi prego potete revisionare i miei FIle ? ciao a tutti, vi comunico un errore di leggibilità tra db e i file che stiamo creando, nel db abbiamo scritto le cose con struttura ciao_ciao_ciao , mentre nel progetto ciaoCiaoCiao. attenti. Poi cambierei anche alcune cose ad es. in valutazione metterei UNIQUE per le 3 chiavi esterne. Ciao buon dicembre

2024-12-09 11:46 UTC, gxanlvxgx commented on Application/src/main/java/model/Valutazione/ValutazioneDAO.java
> +    public synchronized void save(ValutazioneBean valutazione) throws SQLException {
Vedi come abbiamo fatto io, carmine e andrea per il try (ovvero aggiungi il finally) perché ConDB è un pool di connessioni che le salva in una lista facendo ConDB.releaseConnection invece di chiuderle, se la chiudi poi ne si viene a creare un'altra successivamente e si perde il vantaggio del pool di connessioni

2024-12-09 11:49 UTC, andr3w003 requested changes
L'id counter non serve, è già gestito automaticamente da mysql;

Serve invece un costruttore che prende l'ID come parametro per poter effettuare l'update (dopo averne preso una ValutazioneBean con get dal DAO), oppure un costruttore che prende direttamente un ResultSet come parametro e va a settare l'ID dal ResultSet

2024-12-09 11:49 UTC, andr3w003 commented on Application/src/main/java/model/Valutazione/ValutazioneBean.java
> +    private static int idCounter = 1; // Variabile statica per calcolare l'ID automaticamente
```suggestion

```

2024-12-09 11:49 UTC, andr3w003 commented on Application/src/main/java/model/Valutazione/ValutazioneBean.java
> +        this.id = idCounter++;
```suggestion

```

2024-12-09 11:49 UTC, andr3w003 commented on Application/src/main/java/model/Valutazione/ValutazioneDAO.java
> +                    );
Bisogna aggiungere anche l'ID al Bean che viene creato

2024-12-09 11:49 UTC, andr3w003 commented on Application/src/main/java/model/Valutazione/ValutazioneDAO.java
> +                ));
Anche qua bisogna aggiungere l'ID

2024-12-09 11:49 UTC, andr3w003 commented on Application/src/main/java/model/Valutazione/ValutazioneBean.java
> +
Da aggiungere costruttore con ResultSet, o modificare il costruttore esistente aggiungendo anche l'ID come parametro

2024-12-10 22:06 UTC, andr3w003 approved these changes

2024-12-10 22:06 UTC, merged